#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# Configuration
# ============================================================

SUBSCRIPTION_ID="f0763483-cdd5-41ff-a288-256f6bc9cc63"
LOCATION="southafricanorth"

BOOTSTRAP_RG="rg-tfstate-devops"
STATE_STORAGE="stcicdstatedev001"
STATE_CONTAINER="tfstate"

APP_NAME="app-cicd-azuredevops"

# Values generated by the Azure DevOps service connection
ADO_ISSUER="https://login.microsoftonline.com/dfc75875-1e90-452b-ac8c-c32745f2d87f/v2.0"
ADO_SUBJECT="/eid1/c/pub/t/dVjH35AeK0WsjMMnRfLYfw/a/rISbSSETf0KqFyZ8ppdXmA/sc/785e96f4-f5af-43ab-a578-e93f975146f5/f86dcace-4e68-4b27-9347-70e9ac2ee2da"

# ============================================================
# Azure
# ============================================================

az account set \
  --subscription "$SUBSCRIPTION_ID"

# ============================================================
# Resource Group
# ============================================================

az group create \
  --name "$BOOTSTRAP_RG" \
  --location "$LOCATION"

# ============================================================
# Terraform State Storage
# ============================================================

az storage account create \
  --name "$STATE_STORAGE" \
  --resource-group "$BOOTSTRAP_RG" \
  --location "$LOCATION" \
  --sku Standard_LRS \
  --kind StorageV2 \
  --min-tls-version TLS1_2 \
  --allow-blob-public-access false \
  --https-only true

az storage container create \
  --name "$STATE_CONTAINER" \
  --account-name "$STATE_STORAGE" \
  --auth-mode login \
  --public-access off

# ============================================================
# Entra App Registration
# ============================================================

APP_ID=$(az ad app create \
  --display-name "$APP_NAME" \
  --sign-in-audience AzureADMyOrg \
  --query appId \
  --output tsv)

echo "Azure DevOps Application ID: $APP_ID"

# ============================================================
# Service Principal
# ============================================================

SP_OBJECT_ID=$(az ad sp create \
  --id "$APP_ID" \
  --query id \
  --output tsv)

# ============================================================
# Azure DevOps Federated Credential
# ============================================================

cat > azure-devops-federated-credential.json <<EOF
{
  "name": "azure-devops-production",
  "issuer": "$ADO_ISSUER",
  "subject": "$ADO_SUBJECT",
  "description": "Azure DevOps production service connection",
  "audiences": [
    "api://AzureADTokenExchange"
  ]
}
EOF

az ad app federated-credential create \
  --id "$APP_ID" \
  --parameters azure-devops-federated-credential.json

rm azure-devops-federated-credential.json

# ============================================================
# RBAC
# ============================================================

az role assignment create \
  --assignee-object-id "$SP_OBJECT_ID" \
  --assignee-principal-type ServicePrincipal \
  --role Contributor \
  --scope "/subscriptions/$SUBSCRIPTION_ID"

echo
echo "=========================================="
echo "Azure DevOps Bootstrap Complete"
echo "=========================================="
echo "Application ID: $APP_ID"
echo "Service Principal: $SP_OBJECT_ID"
echo "State Storage: $STATE_STORAGE"
echo "State Container: $STATE_CONTAINER"